import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve('dist');
const pages = [
  'index.html', 'learn.html', 'hubs.html', 'tools.html', 'research.html', 'model.html', 'assessment.html', 'readiness.html',
  'articles/revops-operating-system.html', 'articles/pipeline-system-problem.html', 'articles/revenue-handoffs.html',
  'articles/crm-adoption-design.html', 'articles/ai-ready-revenue-system.html'
];

const t = new Map(Object.entries({
  'Skip to content': 'Saltar para o conteúdo', 'Menu': 'Menu', 'Learn': 'Aprender', 'Hubs': 'Hubs', 'Fundamentals': 'Fundamentos', 'Tools': 'Ferramentas', 'Research': 'Investigação', 'Methodology': 'Metodologia',
  'Main navigation': 'Navegação principal', 'RevOpHubs home': 'Página inicial da RevOpHubs', 'Revenue Systems Brief newsletter': 'Newsletter Revenue Systems Brief', 'Strategy, Process, CRM, Data, Automation and AI lead to Revenue': 'Estratégia, Processo, CRM, Dados, Automação e IA conduzem à Receita', 'Knowledge sections': 'Secções de conhecimento', 'Model layers': 'Camadas do modelo',
  'Independent Revenue Operations research, practical frameworks and diagnostic tools for building a connected revenue system.': 'Investigação independente de Revenue Operations, modelos práticos e ferramentas de diagnóstico para construir um sistema de receita conectado.',
  'Practical Revenue Operations guides organised around strategy, process, CRM, data, automation and AI.': 'Guias práticos de Revenue Operations organizados em torno de estratégia, processo, CRM, dados, automação e IA.',
  'Explore connected knowledge hubs for revenue strategy, process, CRM, data, automation and AI.': 'Explore hubs de conhecimento conectados sobre estratégia de receita, processo, CRM, dados, automação e IA.',
  'Practical tools for assessing a revenue system, exploring its dependencies and preparing CRM change.': 'Ferramentas práticas para avaliar um sistema de receita, explorar as suas dependências e preparar uma mudança de CRM.',
  'The principles and research agenda behind RevOpHubs.': 'Os princípios e a agenda de investigação da RevOpHubs.', 'Explore the six connected layers of an operational revenue system: strategy, process, CRM, data, automation and AI.': 'Explore as seis camadas conectadas de um sistema de receita operacional: estratégia, processo, CRM, dados, automação e IA.',
  'A directional diagnostic across strategy, process, CRM, data, automation and AI.': 'Um diagnóstico indicativo de estratégia, processo, CRM, dados, automação e IA.', 'Check whether your organisation is ready to redesign or migrate its CRM.': 'Verifique se a sua organização está preparada para redesenhar ou migrar o CRM.',
  'A practical definition of Revenue Operations as the system connecting strategy, process, CRM, data, automation and AI.': 'Uma definição prática de Revenue Operations como o sistema que liga estratégia, processo, CRM, dados, automação e IA.', 'How to distinguish a demand problem from a conversion, process or data problem before increasing pipeline.': 'Como distinguir um problema de procura de um problema de conversão, processo ou dados antes de aumentar o pipeline.', 'A practical method for finding and repairing revenue loss between marketing, sales and customer teams.': 'Um método prático para encontrar e reparar perdas de receita entre marketing, vendas e equipas de clientes.', 'Why CRM adoption depends on operating design, user value and governance — not training alone.': 'Porque a adoção do CRM depende do desenho operacional, do valor para o utilizador e da governação — não apenas da formação.', 'The operational conditions that make AI reliable, governed and useful across a revenue system.': 'As condições operacionais que tornam a IA fiável, governada e útil em todo o sistema de receita.',
  'Foundation · 10 min read': 'Fundamentos · 10 min de leitura', 'Strategy · 8 min read': 'Estratégia · 8 min de leitura', 'Process · 8 min read': 'Processo · 8 min de leitura', 'CRM · 9 min read': 'CRM · 9 min de leitura', 'AI · 9 min read': 'IA · 9 min de leitura',
  'Assess your Revenue System →': 'Avaliar o seu sistema de receita →', 'Start the assessment →': 'Iniciar o diagnóstico →', 'Why more pipeline does not solve a system problem →': 'Porque é que mais pipeline não resolve um problema de sistema →', 'Revenue leaks at the hand-offs →': 'A receita perde-se nas passagens de trabalho →', 'CRM adoption is an operating-design issue →': 'A adoção do CRM é uma questão de desenho operacional →',
  'Assessment': 'Diagnóstico', 'Assess your Revenue System': 'Avaliar o seu sistema de receita', 'Revenue System Assessment': 'Diagnóstico do sistema de receita',
  'Strategy': 'Estratégia', 'Process': 'Processo', 'Data': 'Dados', 'Automation': 'Automação', 'Revenue': 'Receita', 'Outcome': 'Resultado',
  'Explore': 'Explorar', 'Apply': 'Aplicar', 'About': 'Sobre', 'Contact': 'Contacto', 'Knowledge hubs': 'Hubs de conhecimento',
  'Independent knowledge for connected revenue systems.': 'Conhecimento independente para sistemas de receita conectados.',
  'Revenue Operations, made operational.': 'Revenue Operations, na prática.',
  'RevOpHubs — Revenue Operations, made operational': 'RevOpHubs — Revenue Operations, na prática',
  'Revenue Operations, made operational': 'Revenue Operations, na prática',
  'Your revenue problem might be a systems problem.': 'O seu problema de receita pode ser um problema de sistema.',
  'RevOpHubs helps B2B teams connect strategy, process, CRM, data, automation and AI into one revenue system — then improve the parts that hold growth back.': 'A RevOpHubs ajuda equipas B2B a ligar estratégia, processo, CRM, dados, automação e IA num único sistema de receita — e a melhorar as partes que limitam o crescimento.',
  'Explore the model': 'Explorar o modelo', 'Revenue Systems Brief': 'Revenue Systems Brief', 'One useful idea. One system to improve.': 'Uma ideia útil. Um sistema para melhorar.',
  'A concise field note for people responsible for revenue, operations and growth.': 'Uma nota de campo concisa para quem é responsável por receita, operações e crescimento.',
  'Subscribe on LinkedIn': 'Subscrever no LinkedIn', '01 / The problem': '01 / O problema', 'Revenue breaks between functions, not inside them.': 'A receita perde-se entre funções, não dentro delas.',
  'Marketing can generate demand. Sales can close. Customer teams can retain. Yet revenue still leaks when the hand-offs, definitions and data between them do not form a coherent system.': 'O marketing pode gerar procura. As vendas podem fechar negócios. As equipas de clientes podem reter. Ainda assim, a receita perde-se quando as passagens de trabalho, as definições e os dados entre estas equipas não formam um sistema coerente.',
  'Disconnected strategy': 'Estratégia desligada', 'Teams optimise local targets without a shared commercial direction.': 'As equipas otimizam objetivos locais sem uma direção comercial partilhada.',
  'Unclear process': 'Processo pouco claro', 'Critical decisions depend on memory, heroics and inconsistent hand-offs.': 'As decisões críticas dependem da memória, de esforços heroicos e de passagens de trabalho inconsistentes.',
  'Untrusted data': 'Dados pouco fiáveis', 'Reports describe activity, but rarely explain what should happen next.': 'Os relatórios descrevem atividade, mas raramente explicam o que deve acontecer a seguir.',
  'Tool-led change': 'Mudança orientada por ferramentas', 'Technology is added before the operating model is ready to support it.': 'A tecnologia é acrescentada antes de o modelo operacional estar preparado para a suportar.',
  '02 / The model': '02 / O modelo', 'The Revenue System Model': 'O modelo do sistema de receita',
  'Six connected operational layers turn commercial intent into repeatable revenue. Revenue is the outcome — not another silo.': 'Seis camadas operacionais conectadas transformam a intenção comercial em receita repetível. A receita é o resultado — não mais um silo.',
  'Understand how the layers work together': 'Perceber como as camadas funcionam em conjunto', '03 / Diagnostic': '03 / Diagnóstico',
  'Where is your revenue system weakest?': 'Onde é que o seu sistema de receita é mais frágil?',
  'Get a directional view across the six layers. The assessment takes about four minutes and turns symptoms into a practical starting point.': 'Obtenha uma leitura indicativa das seis camadas. O diagnóstico demora cerca de quatro minutos e transforma sintomas num ponto de partida prático.',
  'Start the assessment': 'Iniciar o diagnóstico', '04 / Knowledge hubs': '04 / Hubs de conhecimento', 'Follow the system, not the noise.': 'Siga o sistema, não o ruído.',
  'Each hub connects foundational thinking, operating guidance and the next practical action.': 'Cada hub liga pensamento fundamental, orientação operacional e a próxima ação prática.',
  'Hub 01': 'Hub 01', 'Hub 02': 'Hub 02', 'Hub 03': 'Hub 03', 'Hub 04': 'Hub 04', 'Revenue Strategy': 'Estratégia de receita',
  'ICP, value, routes to market and commercial priorities.': 'ICP, valor, rotas para o mercado e prioridades comerciais.', 'Enter hub →': 'Entrar no hub →',
  'Process &amp; Governance': 'Processo e governação', 'Lifecycle, ownership, hand-offs and decision rights.': 'Ciclo de vida, responsabilidade, passagens de trabalho e direitos de decisão.',
  'CRM &amp; Data': 'CRM e dados', 'Architecture, adoption, measurement and trust.': 'Arquitetura, adoção, medição e confiança.',
  'Automation &amp; AI': 'Automação e IA', 'Operational leverage built on a system that is ready.': 'Capacidade operacional construída sobre um sistema preparado.',
  '05 / Tools': '05 / Ferramentas', 'Turn understanding into action.': 'Transforme compreensão em ação.',
  'Use practical diagnostics and working tools to identify the next constraint, not another generic best practice.': 'Use diagnósticos práticos e ferramentas de trabalho para identificar a próxima limitação, em vez de mais uma boa prática genérica.',
  'Identify strengths, gaps and receive a 30-day plan for the weakest layer.': 'Identifique pontos fortes e lacunas e receba um plano de 30 dias para a camada mais frágil.',
  'Open tool →': 'Abrir ferramenta →', 'Revenue System Explorer': 'Explorador do sistema de receita', 'See the role, dependencies and failure signals of every layer.': 'Veja o papel, as dependências e os sinais de falha de cada camada.',
  'Explore →': 'Explorar →', 'CRM Readiness Check': 'Teste de preparação do CRM', 'Test the conditions for a CRM redesign or migration before configuration begins.': 'Teste as condições para redesenhar ou migrar o CRM antes de iniciar a configuração.',
  '06 / Learn': '06 / Aprender', 'Start with the system.': 'Comece pelo sistema.', 'Browse all guides →': 'Ver todos os guias →', 'Start here · 10 min': 'Começar aqui · 10 min',
  'RevOps is not a department. It is an operating system.': 'RevOps não é um departamento. É um sistema operativo.',
  'A practical way to understand Revenue Operations without reducing it to a new reporting line, a CRM project or an automation layer.': 'Uma forma prática de compreender Revenue Operations sem a reduzir a uma nova linha hierárquica, a um projeto de CRM ou a uma camada de automação.',
  'Read the guide →': 'Ler o guia →', 'Strategy · 8 min': 'Estratégia · 8 min', 'Why more pipeline does not solve a system problem': 'Porque é que mais pipeline não resolve um problema de sistema',
  'Separating a demand problem from a conversion, process or data problem.': 'Distinguir um problema de procura de um problema de conversão, processo ou dados.', 'CRM · 9 min': 'CRM · 9 min',
  'CRM adoption is an operating-design issue': 'A adoção do CRM é uma questão de desenho operacional', 'What teams miss when they treat adoption as a training problem.': 'O que as equipas ignoram quando tratam a adoção como um problema de formação.',
  '07 / Research': '07 / Investigação', 'Evidence before opinion.': 'Evidência antes da opinião.',
  'RevOpHubs studies how B2B organisations design, connect and evolve their revenue systems — including the organisational conditions that make AI useful.': 'A RevOpHubs estuda como as organizações B2B desenham, ligam e desenvolvem os seus sistemas de receita — incluindo as condições organizacionais que tornam a IA útil.',
  'See our research principles →': 'Ver os nossos princípios de investigação →', '“The goal is not to automate more work. It is to design a revenue system worth automating.”': '“O objetivo não é automatizar mais trabalho. É desenhar um sistema de receita que valha a pena automatizar.”',
  'RevOpHubs principle 01': 'Princípio RevOpHubs 01', 'A practical starting point': 'Um ponto de partida prático', 'See your revenue system as a system.': 'Veja o seu sistema de receita como um sistema.',
  'Build a shared view of what is working, where revenue is leaking and what to improve next.': 'Crie uma visão partilhada do que funciona, de onde a receita se perde e do que deve melhorar a seguir.',
  'One useful idea for improving how revenue works.': 'Uma ideia útil para melhorar a forma como a receita funciona.',

  'Learn Revenue Operations — RevOpHubs': 'Aprender Revenue Operations — RevOpHubs', 'Build the system before optimising the parts.': 'Construa o sistema antes de otimizar as partes.',
  'Guides for understanding how revenue work fits together — and deciding what to improve next.': 'Guias para compreender como o trabalho de receita se articula — e decidir o que melhorar a seguir.',
  'Start here': 'Começar aqui', 'Operations': 'Operações', 'Technology': 'Tecnologia', 'A guided starting path': 'Um percurso inicial guiado',
  'Three pieces that establish the model, reveal the common failure pattern and show where technology belongs.': 'Três conteúdos que estabelecem o modelo, revelam o padrão comum de falha e mostram onde a tecnologia se enquadra.',
  'Step 01 · Foundation': 'Passo 01 · Fundamentos', 'RevOps is an operating system': 'RevOps é um sistema operativo', 'Move beyond the idea of RevOps as a team, title or reporting function.': 'Vá além da ideia de RevOps como equipa, cargo ou função de reporting.',
  'Step 02 · Diagnosis': 'Passo 02 · Diagnóstico', 'Pipeline cannot fix a system problem': 'O pipeline não resolve um problema de sistema', 'Learn to distinguish a demand problem from a process or conversion problem.': 'Aprenda a distinguir um problema de procura de um problema de processo ou conversão.',
  'Step 03 · Leverage': 'Passo 03 · Capacidade', 'AI starts before the AI layer': 'A IA começa antes da camada de IA', 'Why process clarity and data quality determine whether AI becomes useful.': 'Porque é que a clareza do processo e a qualidade dos dados determinam se a IA se torna útil.',
  'Strategy and operating design': 'Estratégia e desenho operacional', 'Choices, ownership and the architecture that connects commercial work.': 'Escolhas, responsabilidade e a arquitetura que liga o trabalho comercial.',
  'Foundation · 10 min': 'Fundamentos · 10 min', 'A practical definition that connects strategy, process, CRM, data, automation and AI.': 'Uma definição prática que liga estratégia, processo, CRM, dados, automação e IA.',
  'Read article →': 'Ler artigo →', 'How to identify the real constraint before increasing demand.': 'Como identificar a verdadeira limitação antes de aumentar a procura.',
  'Process · 8 min': 'Processo · 8 min', 'Revenue leaks at the hand-offs': 'A receita perde-se nas passagens de trabalho', 'A method for finding the gaps between marketing, sales and customer success.': 'Um método para encontrar as lacunas entre marketing, vendas e customer success.',
  'CRM, data and AI': 'CRM, dados e IA', 'Technology becomes leverage only when it expresses a coherent operating model.': 'A tecnologia só cria capacidade quando expressa um modelo operacional coerente.',
  'Why training cannot compensate for a CRM that does not help people work.': 'Porque a formação não compensa um CRM que não ajuda as pessoas a trabalhar.',
  'AI · 9 min': 'IA · 9 min', 'AI readiness starts before the AI layer': 'A preparação para IA começa antes da camada de IA', 'The operational conditions that make AI reliable, governed and useful.': 'As condições operacionais que tornam a IA fiável, governada e útil.',
  'Tool · 5 min': 'Ferramenta · 5 min', 'Is your CRM ready for redesign?': 'O seu CRM está preparado para ser redesenhado?', 'Use the readiness checklist before buying, migrating or rebuilding.': 'Use a checklist de preparação antes de comprar, migrar ou reconstruir.',

  'Revenue Operations Knowledge Hubs — RevOpHubs': 'Hubs de conhecimento de Revenue Operations — RevOpHubs', 'Knowledge hubs': 'Hubs de conhecimento',
  'Enter through one layer. Understand the whole system.': 'Entre por uma camada. Compreenda todo o sistema.', 'Each hub combines a core question, failure signals, practical guidance and the tool that helps you act.': 'Cada hub combina uma pergunta central, sinais de falha, orientação prática e a ferramenta que o ajuda a agir.',
  'ICP, value, routes to market and the choices that give the rest of the system direction.': 'ICP, valor, rotas para o mercado e as escolhas que dão direção ao resto do sistema.', 'Explore the hub →': 'Explorar o hub →',
  'Lifecycle stages, ownership, decision rights and the hand-offs where revenue commonly leaks.': 'Etapas do ciclo de vida, responsabilidade, direitos de decisão e as passagens de trabalho onde a receita habitualmente se perde.',
  'The operational environment for shared work, evidence, next actions and adoption.': 'O ambiente operacional para trabalho partilhado, evidência, próximas ações e adoção.', 'Revenue Data': 'Dados de receita',
  'Common definitions, reliable capture and measures that lead to decisions rather than debate.': 'Definições comuns, recolha fiável e métricas que conduzem a decisões em vez de debate.',
  'Removing delay and repetition from processes that are understood and governed.': 'Remover atrasos e repetição de processos compreendidos e governados.', 'AI in Revenue': 'IA na receita',
  'Using trusted context, human ownership and operational readiness to create real leverage.': 'Usar contexto fiável, responsabilidade humana e preparação operacional para criar capacidade real.',
  'Not sure where to start?': 'Não sabe por onde começar?', 'Let the weakest layer choose the hub.': 'Deixe que a camada mais frágil escolha o hub.', 'The assessment maps your answers to the most relevant starting point.': 'O diagnóstico associa as suas respostas ao ponto de partida mais relevante.',

  'Revenue Operations Tools — RevOpHubs': 'Ferramentas de Revenue Operations — RevOpHubs', 'Diagnose before you optimise.': 'Diagnostique antes de otimizar.',
  'Small, focused tools for finding the next constraint and turning a broad RevOps problem into a practical decision.': 'Ferramentas pequenas e focadas para encontrar a próxima limitação e transformar um problema amplo de RevOps numa decisão prática.',
  'Diagnostic': 'Diagnóstico', 'Live': 'Disponível', 'Score six operating layers, identify the weakest constraint and receive a personalised 30-day starting plan.': 'Avalie seis camadas operacionais, identifique a limitação mais frágil e receba um plano inicial personalizado de 30 dias.',
  'Start assessment →': 'Iniciar diagnóstico →', 'Explorer': 'Explorador', 'Understand the role, dependencies and failure signals of Strategy, Process, CRM, Data, Automation and AI.': 'Compreenda o papel, as dependências e os sinais de falha de Estratégia, Processo, CRM, Dados, Automação e IA.',
  'Explore the model →': 'Explorar o modelo →', 'Checklist': 'Checklist', 'Test whether your team is ready to redesign or migrate its CRM — before the technology decision takes over.': 'Teste se a sua equipa está preparada para redesenhar ou migrar o CRM — antes que a decisão tecnológica domine o projeto.',
  'Check CRM readiness →': 'Testar a preparação do CRM →', 'Mapping tool': 'Ferramenta de mapeamento', 'Next': 'Em breve', 'Revenue Hand-off Mapper': 'Mapeador de passagens de trabalho de receita',
  'Map ownership, information and exit criteria across the customer lifecycle. Currently being developed from the hand-off method.': 'Mapeie responsabilidade, informação e critérios de saída ao longo do ciclo de vida do cliente. Em desenvolvimento com base no método de passagens de trabalho.', 'Learn the method →': 'Conhecer o método →',

  'Research Principles — RevOpHubs': 'Princípios de investigação — RevOpHubs', 'Evidence before opinion. Systems before tools.': 'Evidência antes da opinião. Sistemas antes das ferramentas.',
  'RevOpHubs studies how B2B organisations connect commercial work — and which conditions make automation and AI genuinely useful.': 'A RevOpHubs estuda como as organizações B2B ligam o trabalho comercial — e quais as condições que tornam a automação e a IA genuinamente úteis.',
  'How the work is approached': 'Como abordamos o trabalho', 'A public methodology for separating observation, inference and recommendation.': 'Uma metodologia pública para separar observação, inferência e recomendação.',
  'Start with observable behaviour': 'Começar pelo comportamento observável', 'Look at how work moves, where decisions stall and which information disappears between teams.': 'Observar como o trabalho avança, onde as decisões bloqueiam e que informação desaparece entre equipas.',
  'Separate symptoms from constraints': 'Separar sintomas de limitações', 'Low pipeline, poor adoption and unreliable forecasts can originate in very different layers.': 'Pipeline reduzido, baixa adoção e previsões pouco fiáveis podem ter origem em camadas muito diferentes.',
  'Prefer connected evidence': 'Preferir evidência conectada', 'Combine operating data, process observation and qualitative context instead of treating one dashboard as truth.': 'Combinar dados operacionais, observação do processo e contexto qualitativo em vez de tratar um dashboard como verdade.',
  'Make recommendations testable': 'Tornar as recomendações testáveis', 'Every recommendation should imply a change in behaviour, a measure and a reasonable review window.': 'Cada recomendação deve implicar uma mudança de comportamento, uma métrica e um período razoável de revisão.',
  'Current research questions': 'Questões de investigação atuais', 'The publication develops these questions through field notes, structured guides and diagnostic tools.': 'A publicação desenvolve estas questões através de notas de campo, guias estruturados e ferramentas de diagnóstico.',
  'AI readiness': 'Preparação para IA', 'Which operating conditions predict whether AI creates capacity or merely produces more output?': 'Que condições operacionais permitem prever se a IA cria capacidade ou apenas produz mais resultados?',
  'Read foundation →': 'Ler fundamentos →', 'CRM adoption': 'Adoção do CRM', 'How much of adoption is explained by interface training, and how much by the quality of operating design?': 'Que parte da adoção é explicada pela formação na interface e que parte resulta da qualidade do desenho operacional?',
  'Cross-functional loss': 'Perda entre funções', 'Where does value disappear between marketing, sales and customer teams — and how can it be observed?': 'Onde desaparece o valor entre marketing, vendas e equipas de clientes — e como pode ser observado?',

  'The Revenue System Model — RevOpHubs': 'O modelo do sistema de receita — RevOpHubs', 'Six layers. One connected revenue system.': 'Seis camadas. Um sistema de receita conectado.',
  'The model separates the operating layers of revenue without treating them as independent functions. Each layer depends on the quality of the one before it. Revenue is the observable outcome.': 'O modelo separa as camadas operacionais da receita sem as tratar como funções independentes. Cada camada depende da qualidade da anterior. A receita é o resultado observável.',
  'Assess your system': 'Avaliar o seu sistema', 'Read the foundation guide →': 'Ler o guia fundamental →', 'Failure signals': 'Sinais de falha',
  'Strategy defines who the system is built to serve, what value it creates and where the organisation will focus. It establishes the commercial choices that every downstream layer must support.': 'A estratégia define quem o sistema serve, que valor cria e onde a organização se concentra. Estabelece as escolhas comerciais que todas as camadas seguintes têm de suportar.',
  'Everyone is a potential customer': 'Todos são potenciais clientes', 'Priorities change by channel or team': 'As prioridades mudam por canal ou equipa', 'Activity is mistaken for progress': 'A atividade é confundida com progresso',
  'Process turns commercial choices into repeatable work. It defines stages, decisions, ownership and hand-offs across the full customer lifecycle.': 'O processo transforma escolhas comerciais em trabalho repetível. Define etapas, decisões, responsabilidade e passagens de trabalho ao longo de todo o ciclo de vida do cliente.',
  'Stages mean different things to different teams': 'As etapas têm significados diferentes para equipas diferentes', 'Critical work depends on individual memory': 'O trabalho crítico depende da memória individual', 'Hand-offs create delay and lost context': 'As passagens de trabalho criam atrasos e perda de contexto',
  'CRM is the operational expression of the process: the shared environment in which work, evidence and next actions become visible. Adoption follows usefulness and design.': 'O CRM é a expressão operacional do processo: o ambiente partilhado onde o trabalho, a evidência e as próximas ações se tornam visíveis. A adoção resulta da utilidade e do desenho.',
  'The CRM records history but does not guide work': 'O CRM regista o histórico, mas não orienta o trabalho', 'Teams maintain private spreadsheets': 'As equipas mantêm folhas de cálculo privadas', 'Required fields do not support decisions': 'Os campos obrigatórios não suportam decisões',
  'Data makes system behaviour measurable. It needs common definitions, reliable capture and a clear relationship to the decisions the organisation must make.': 'Os dados tornam o comportamento do sistema mensurável. Exigem definições comuns, recolha fiável e uma relação clara com as decisões que a organização tem de tomar.',
  'Reports disagree on basic numbers': 'Os relatórios discordam nos números básicos', 'Metrics describe volume without quality': 'As métricas descrevem volume sem qualidade', 'Teams debate data instead of decisions': 'As equipas discutem dados em vez de decisões',
  'Automation removes delay and manual repetition from a process that is already understood. It scales operating discipline; it cannot create it.': 'A automação remove atrasos e repetição manual de um processo já compreendido. Amplia a disciplina operacional; não a consegue criar.',
  'Automations reproduce unclear rules': 'As automações reproduzem regras pouco claras', 'Exceptions accumulate without ownership': 'As exceções acumulam-se sem responsável', 'Tools add activity but little capacity': 'As ferramentas acrescentam atividade, mas pouca capacidade',
  'AI adds interpretation, generation and adaptive action where the system has sufficient context, quality and governance. Its value depends on the maturity of every previous layer.': 'A IA acrescenta interpretação, geração e ação adaptativa quando o sistema tem contexto, qualidade e governação suficientes. O seu valor depende da maturidade de todas as camadas anteriores.',
  'AI tools operate outside core workflows': 'As ferramentas de IA operam fora dos fluxos de trabalho principais', 'Outputs lack trusted context': 'Os resultados não têm contexto fiável', 'Experiments have no operational owner': 'As experiências não têm responsável operacional',
  'Revenue is not the seventh function. It is the output of the entire system: the result of connected choices, behaviours, information and leverage.': 'A receita não é a sétima função. É o resultado de todo o sistema: escolhas, comportamentos, informação e capacidade conectados.',
  'What to observe': 'O que observar', 'Conversion across the full lifecycle': 'Conversão ao longo de todo o ciclo de vida', 'Speed, predictability and quality': 'Velocidade, previsibilidade e qualidade', 'Retention, expansion and learning': 'Retenção, expansão e aprendizagem',
  'Apply the model': 'Aplicar o modelo', 'Find the constraint before choosing the solution.': 'Encontre a limitação antes de escolher a solução.', 'Use the assessment to identify which layer deserves attention first.': 'Use o diagnóstico para identificar que camada merece atenção primeiro.',

  'Revenue System Assessment — RevOpHubs': 'Diagnóstico do sistema de receita — RevOpHubs', 'Find the layer that is limiting the system.': 'Encontre a camada que está a limitar o sistema.',
  'Answer six practical questions for a directional view of your revenue system. This is a starting point, not a maturity badge.': 'Responda a seis perguntas práticas para obter uma leitura indicativa do seu sistema de receita. É um ponto de partida, não um selo de maturidade.',
  'Question 1 of 6': 'Pergunta 1 de 6', 'About 4 minutes': 'Cerca de 4 minutos',
  'How clearly has your organisation defined where revenue should come from?': 'Com que clareza definiu a sua organização de onde deve vir a receita?', 'Priorities change frequently and differ by team.': 'As prioridades mudam frequentemente e diferem entre equipas.', 'We have target markets, but focus is still broad or inconsistent.': 'Temos mercados-alvo, mas o foco ainda é amplo ou inconsistente.', 'Our ICP, value proposition and routes to market guide real trade-offs.': 'O nosso ICP, a proposta de valor e as rotas para o mercado orientam escolhas reais.', 'Strategy is explicit, measured and regularly refined with evidence.': 'A estratégia é explícita, medida e aperfeiçoada regularmente com evidência.',
  'How consistently does work move across the customer lifecycle?': 'Com que consistência avança o trabalho ao longo do ciclo de vida do cliente?', 'Outcomes depend mainly on individual effort and memory.': 'Os resultados dependem sobretudo do esforço individual e da memória.', 'Some stages exist, but ownership and hand-offs are uneven.': 'Existem algumas etapas, mas a responsabilidade e as passagens de trabalho são irregulares.', 'Stages, owners and decision criteria are shared and followed.': 'As etapas, os responsáveis e os critérios de decisão são partilhados e cumpridos.', 'The lifecycle is governed, measured and improved as one system.': 'O ciclo de vida é governado, medido e melhorado como um único sistema.',
  'How useful is your CRM in guiding everyday commercial work?': 'Até que ponto o seu CRM é útil para orientar o trabalho comercial diário?', 'It is mostly an incomplete record required by management.': 'É sobretudo um registo incompleto exigido pela gestão.', 'Core data exists, but teams still work around the CRM.': 'Os dados essenciais existem, mas as equipas continuam a contornar o CRM.', 'The CRM supports the process and makes next actions visible.': 'O CRM suporta o processo e torna visíveis as próximas ações.', 'It is the trusted operational layer across the customer lifecycle.': 'É a camada operacional de confiança ao longo do ciclo de vida do cliente.',
  'How confidently can teams use revenue data to make decisions?': 'Com que confiança podem as equipas usar dados de receita para tomar decisões?', 'Basic numbers are incomplete or regularly disputed.': 'Os números básicos estão incompletos ou são contestados regularmente.', 'Activity is visible, but quality and causality are unclear.': 'A atividade é visível, mas a qualidade e a causalidade não são claras.', 'Definitions are shared and reporting supports key decisions.': 'As definições são partilhadas e o reporting suporta decisões essenciais.', 'Reliable data drives planning, action and continuous learning.': 'Dados fiáveis orientam o planeamento, a ação e a aprendizagem contínua.',
  'How intentionally is automation used across revenue work?': 'Com que intencionalidade é usada a automação no trabalho de receita?', 'Automation is minimal or consists of disconnected experiments.': 'A automação é mínima ou consiste em experiências isoladas.', 'Some repetitive work is automated, with uneven governance.': 'Algum trabalho repetitivo está automatizado, com governação irregular.', 'Automation follows defined processes and removes real friction.': 'A automação segue processos definidos e remove fricção real.', 'Automations are governed, measured and designed across functions.': 'As automações são governadas, medidas e desenhadas entre funções.',
  'How deeply is AI connected to trusted workflows and context?': 'Até que ponto a IA está ligada a fluxos de trabalho e contexto fiáveis?', 'Use is individual, ad hoc and outside core workflows.': 'A utilização é individual, pontual e fora dos fluxos de trabalho principais.', 'Teams have useful experiments, but limited shared context.': 'As equipas têm experiências úteis, mas pouco contexto partilhado.', 'AI supports defined work with human review and clear ownership.': 'A IA suporta trabalho definido com revisão humana e responsabilidade clara.', 'AI is governed as an adaptive layer of the revenue system.': 'A IA é governada como uma camada adaptativa do sistema de receita.',
  'Back': 'Anterior', 'Next question': 'Pergunta seguinte', 'Directional system score': 'Pontuação indicativa do sistema', 'Your system has a foundation to build on.': 'O seu sistema tem uma base para desenvolver.', 'Copy result': 'Copiar resultado', 'Download result': 'Descarregar resultado', 'Discuss the result': 'Conversar sobre o resultado',
  'What you will get': 'O que vai receber', 'A simple directional score and a layer-by-layer view to support a better first conversation.': 'Uma pontuação indicativa simples e uma visão camada a camada para apoiar uma primeira conversa mais útil.', 'No registration required': 'Sem registo', 'Six operational layers': 'Seis camadas operacionais', 'Your weakest layer highlighted': 'A camada mais frágil em destaque', 'A suggested next focus': 'Uma sugestão para o próximo foco', 'Important:': 'Importante:', 'this first version is a diagnostic guide, not an audited benchmark.': 'esta primeira versão é um guia de diagnóstico, não um benchmark auditado.',

  'CRM Readiness Check — RevOpHubs': 'Teste de preparação do CRM — RevOpHubs', 'Do not redesign the CRM before the organisation is ready.': 'Não redesenhe o CRM antes de a organização estar preparada.', 'Check the operating conditions that should exist before configuration, migration or vendor selection begins.': 'Verifique as condições operacionais que devem existir antes de começar a configuração, a migração ou a seleção de fornecedor.',
  'Commercial clarity': 'Clareza comercial', 'We can state the primary ICP and the commercial motions the CRM must support.': 'Conseguimos indicar o ICP principal e os movimentos comerciais que o CRM tem de suportar.', 'Lifecycle stages have observable entry and exit criteria.': 'As etapas do ciclo de vida têm critérios observáveis de entrada e saída.', 'Marketing, sales and customer teams agree on the core definitions.': 'As equipas de marketing, vendas e clientes concordam com as definições essenciais.',
  'Ownership and governance': 'Responsabilidade e governação', 'Each lifecycle stage and hand-off has a named operational owner.': 'Cada etapa e passagem de trabalho do ciclo de vida tem um responsável operacional identificado.', 'Someone has authority to resolve cross-functional design decisions.': 'Alguém tem autoridade para resolver decisões de desenho entre funções.', 'There is a process for changing fields, stages, automations and reports.': 'Existe um processo para alterar campos, etapas, automações e relatórios.',
  'Data and adoption': 'Dados e adoção', 'We know which data is required for decisions, not merely desirable to collect.': 'Sabemos que dados são necessários para decidir, e não apenas desejáveis de recolher.', 'We understand why users currently work outside the CRM.': 'Compreendemos porque é que os utilizadores trabalham atualmente fora do CRM.', 'Success measures include user behaviour and business outcomes.': 'As métricas de sucesso incluem o comportamento dos utilizadores e os resultados de negócio.',
  'Calculate readiness': 'Calcular preparação', 'Readiness score': 'Pontuação de preparação', 'Read the CRM guide': 'Ler o guia de CRM', 'How to use this': 'Como utilizar', 'Answer based on evidence, not intent. A low score does not mean “do nothing”; it means the next work is operating design rather than configuration.': 'Responda com base em evidência, não em intenção. Uma pontuação baixa não significa “não fazer nada”; significa que o próximo trabalho é o desenho operacional, e não a configuração.', '0–44: design first': '0–44: desenhar primeiro', '45–74: proceed with conditions': '45–74: avançar com condições', '75–100: ready to configure': '75–100: preparado para configurar', 'All tools →': 'Todas as ferramentas →',

  'RevOps Is Not a Department. It Is an Operating System. — RevOpHubs': 'RevOps não é um departamento. É um sistema operativo. — RevOpHubs',
  'The moment Revenue Operations becomes another silo, it starts reproducing the problem it was created to solve.': 'Quando Revenue Operations se torna mais um silo, começa a reproduzir o problema que foi criada para resolver.', 'RevOpHubs field guide · Updated September 2026': 'Guia de campo RevOpHubs · Atualizado em setembro de 2026', 'RevOpHubs field guide · September 2026': 'Guia de campo RevOpHubs · Setembro de 2026',
  'A company can have capable marketers, experienced salespeople, a well-configured CRM and a growing technology stack — and still make revenue feel accidental. The problem is often not the quality of the parts. It is the way the parts behave together.': 'Uma empresa pode ter bons profissionais de marketing, vendedores experientes, um CRM bem configurado e uma stack tecnológica em crescimento — e ainda assim sentir que a receita é acidental. O problema muitas vezes não é a qualidade das partes. É a forma como as partes se comportam em conjunto.',
  'This is where many definitions of Revenue Operations become too narrow. RevOps is described as a team, a reporting line or a collection of specialists who manage CRM, dashboards and automation. Those activities matter, but they do not define the job. They are components of a larger operating system.': 'É aqui que muitas definições de Revenue Operations se tornam demasiado estreitas. RevOps é descrita como uma equipa, uma linha hierárquica ou um conjunto de especialistas que gerem CRM, dashboards e automação. Essas atividades são importantes, mas não definem o trabalho. São componentes de um sistema operativo mais amplo.',
  'The department definition creates the wrong question': 'A definição como departamento cria a pergunta errada', 'When RevOps is treated as a department, leaders ask where it should report, which tools it should own and how many people it needs. These are organisational questions. They do not answer the more important operational question: how should revenue work move across the company?': 'Quando RevOps é tratada como um departamento, os líderes perguntam a quem deve reportar, que ferramentas deve gerir e de quantas pessoas precisa. São perguntas organizacionais. Não respondem à pergunta operacional mais importante: como deve o trabalho de receita avançar na empresa?',
  'A department can own a task. It cannot, by itself, own every decision and hand-off that shapes the customer lifecycle. Marketing defines audiences and creates demand. Sales qualifies, advances and negotiates. Customer teams onboard, retain and expand. Finance establishes commercial controls. Product shapes what can be promised and delivered. Revenue emerges from their combined behaviour.': 'Um departamento pode ser responsável por uma tarefa. Não pode, por si só, ser responsável por todas as decisões e passagens de trabalho que moldam o ciclo de vida do cliente. O marketing define públicos e cria procura. As vendas qualificam, fazem avançar e negoceiam. As equipas de clientes integram, retêm e expandem. As finanças estabelecem controlos comerciais. O produto molda aquilo que pode ser prometido e entregue. A receita resulta do comportamento conjunto de todas estas áreas.',
  'RevOps is the design and governance of that combined behaviour.': 'RevOps é o desenho e a governação desse comportamento conjunto.', 'This changes the unit of analysis. Instead of optimising marketing, sales or customer success in isolation, the organisation observes the system from first signal to retained customer. It looks for delays, conflicting definitions, missing information and incentives that create local wins at the expense of total revenue.': 'Isto muda a unidade de análise. Em vez de otimizar marketing, vendas ou customer success de forma isolada, a organização observa o sistema desde o primeiro sinal até ao cliente retido. Procura atrasos, definições em conflito, informação em falta e incentivos que criam vitórias locais à custa da receita total.',
  'The six operational layers': 'As seis camadas operacionais', 'The Revenue System Model separates the system into six connected layers. Strategy defines where the organisation will focus and what value it intends to create. Process turns those choices into repeatable work. CRM expresses the process in a shared operational environment. Data makes behaviour and outcomes measurable. Automation removes delay and repetition. AI adds interpretation and adaptive action where context and governance are strong enough.': 'O modelo do sistema de receita separa o sistema em seis camadas conectadas. A estratégia define onde a organização se concentra e que valor pretende criar. O processo transforma essas escolhas em trabalho repetível. O CRM expressa o processo num ambiente operacional partilhado. Os dados tornam o comportamento e os resultados mensuráveis. A automação remove atrasos e repetição. A IA acrescenta interpretação e ação adaptativa onde o contexto e a governação são suficientemente sólidos.',
  'The order matters. Technology cannot compensate for ambiguity in the layers before it. A sophisticated CRM built on unclear lifecycle stages produces structured confusion. Automation applied to a broken hand-off makes the failure happen faster. AI connected to unreliable data generates plausible output without dependable judgement.': 'A ordem importa. A tecnologia não consegue compensar a ambiguidade das camadas anteriores. Um CRM sofisticado construído sobre etapas pouco claras produz confusão estruturada. A automação aplicada a uma passagem de trabalho falhada acelera a falha. A IA ligada a dados pouco fiáveis gera resultados plausíveis sem um julgamento seguro.',
  'See the system before choosing the intervention': 'Veja o sistema antes de escolher a intervenção', 'The Revenue System Assessment gives you a directional score across all six layers and identifies the most likely starting constraint.': 'O diagnóstico do sistema de receita fornece uma pontuação indicativa nas seis camadas e identifica a limitação inicial mais provável.',
  'What operating-system thinking changes': 'O que muda quando se pensa em sistema operativo', 'It changes what “alignment” means': 'Muda o significado de “alinhamento”', 'Alignment is not agreement in a meeting. It is consistent behaviour after the meeting: the same definitions, decision criteria, ownership and measures across the relevant teams.': 'Alinhamento não é concordar numa reunião. É ter um comportamento consistente depois da reunião: as mesmas definições, critérios de decisão, responsabilidades e métricas nas equipas relevantes.',
  'It changes the role of the CRM': 'Muda o papel do CRM', 'The CRM stops being a database that managers ask people to update. It becomes the operational expression of the revenue process: a place where the right context is available, the next action is visible and hand-offs can be verified.': 'O CRM deixa de ser uma base de dados que os gestores pedem às pessoas para atualizar. Torna-se a expressão operacional do processo de receita: um lugar onde o contexto certo está disponível, a próxima ação é visível e as passagens de trabalho podem ser verificadas.',
  'It changes how technology is selected': 'Muda a forma de selecionar tecnologia', 'The question is no longer “What can this platform do?” It becomes “Which part of our operating model must this platform support, and how will we know that it is improving the system?”': 'A pergunta deixa de ser “O que consegue fazer esta plataforma?”. Passa a ser “Que parte do nosso modelo operacional deve esta plataforma suportar e como saberemos que está a melhorar o sistema?”.',
  'It changes accountability': 'Muda a responsabilização', 'Cross-functional problems need an owner with authority to resolve them. RevOps can facilitate, diagnose and design, but business leaders remain accountable for the commercial choices and behaviours inside their functions.': 'Os problemas entre funções precisam de um responsável com autoridade para os resolver. RevOps pode facilitar, diagnosticar e desenhar, mas os líderes de negócio continuam responsáveis pelas escolhas e comportamentos comerciais dentro das suas funções.',
  'A practical first move': 'Um primeiro passo prático', 'Do not begin with a transformation programme. Choose one revenue outcome that matters, trace the work required to produce it and identify the most consequential break between teams or layers. Define the current behaviour, the desired behaviour, the owner and one measure that will show whether the system is improving.': 'Não comece por um programa de transformação. Escolha um resultado de receita importante, acompanhe o trabalho necessário para o produzir e identifique a rutura mais relevante entre equipas ou camadas. Defina o comportamento atual, o comportamento desejado, o responsável e uma métrica que mostre se o sistema está a melhorar.',
  'This bounded approach prevents RevOps from becoming an endless clean-up function. It creates a repeatable way to improve the operating system one constraint at a time.': 'Esta abordagem delimitada evita que RevOps se torne uma função interminável de limpeza. Cria uma forma repetível de melhorar o sistema operativo, uma limitação de cada vez.',
  'Continue the path': 'Continuar o percurso', 'Explore all six layers of the model →': 'Explorar as seis camadas do modelo →', 'In this guide': 'Neste guia', 'The department trap': 'A armadilha do departamento', 'Six operational layers': 'Seis camadas operacionais', 'What changes': 'O que muda', 'Apply it': 'Aplicar', 'Find the layer that is limiting your revenue system.': 'Encontre a camada que está a limitar o seu sistema de receita.', 'Take the assessment →': 'Fazer o diagnóstico →', 'Back to Learn': 'Voltar a Aprender',

  'Why More Pipeline Does Not Solve a System Problem — RevOpHubs': 'Porque é que mais pipeline não resolve um problema de sistema — RevOpHubs', 'When revenue misses target, increasing demand feels decisive. It can also hide the constraint and make the system more expensive.': 'Quando a receita falha o objetivo, aumentar a procura parece decisivo. Também pode esconder a limitação e tornar o sistema mais caro.',
  'The revenue number is behind plan. The fastest response is often to ask marketing for more leads, sales for more activity and the team for a new campaign. This response assumes the top of the funnel is the constraint. Sometimes it is. Often, the existing system is already losing too much of the demand it has.': 'A receita está abaixo do plano. A resposta mais rápida costuma ser pedir mais leads ao marketing, mais atividade às vendas e uma nova campanha à equipa. Esta resposta pressupõe que o topo do funil é a limitação. Às vezes é. Muitas vezes, o sistema existente já está a perder demasiada procura.',
  'Adding pipeline to a system with poor qualification, slow follow-up or inconsistent hand-offs does not repair the loss. It feeds it. The organisation may report more activity while customer acquisition costs rise and forecast confidence falls.': 'Acrescentar pipeline a um sistema com má qualificação, follow-up lento ou passagens de trabalho inconsistentes não repara a perda. Alimenta-a. A organização pode reportar mais atividade enquanto os custos de aquisição aumentam e a confiança na previsão diminui.',
  'Start with the shape of the loss': 'Comece pela forma da perda', 'A genuine demand problem has a specific signature: the organisation reaches too few suitable buyers, despite having a credible offer and a reliable path from interest to revenue. A system problem looks different. There may be enough initial demand, but opportunities stall, recycle without learning, arrive poorly qualified or disappear between stages.': 'Um verdadeiro problema de procura tem uma assinatura específica: a organização alcança poucos compradores adequados, apesar de ter uma oferta credível e um caminho fiável do interesse à receita. Um problema de sistema é diferente. Pode existir procura inicial suficiente, mas as oportunidades bloqueiam, regressam sem aprendizagem, chegam mal qualificadas ou desaparecem entre etapas.',
  'Before changing spend, inspect four patterns:': 'Antes de alterar o investimento, analise quatro padrões:', 'Concentration:': 'Concentração:', 'Is the shortfall concentrated in one segment, market or route to market?': 'A quebra está concentrada num segmento, mercado ou rota para o mercado?', 'Stage loss:': 'Perda por etapa:', 'Where does conversion fall most sharply compared with the previous period or a healthy cohort?': 'Onde é que a conversão cai mais em comparação com o período anterior ou uma coorte saudável?', 'Time:': 'Tempo:', 'Where does work wait, and which stage has become slower?': 'Onde fica o trabalho à espera e que etapa se tornou mais lenta?', 'Rework:': 'Retrabalho:', 'How often do teams return records, repeat discovery or correct missing information?': 'Com que frequência as equipas devolvem registos, repetem discovery ou corrigem informação em falta?',
  'Pipeline volume can conceal quality': 'O volume de pipeline pode esconder a qualidade', 'A single pipeline number combines opportunities with different probabilities, fit and evidence. If entry criteria are weak, an organisation can increase pipeline simply by labelling more records as opportunities. The dashboard improves before the business does.': 'Um único número de pipeline combina oportunidades com diferentes probabilidades, adequação e evidência. Se os critérios de entrada forem fracos, uma organização pode aumentar o pipeline simplesmente classificando mais registos como oportunidades. O dashboard melhora antes do negócio.', 'Pipeline is only useful when every stage represents evidence, not optimism.': 'O pipeline só é útil quando cada etapa representa evidência, não otimismo.',
  'This is why stage definitions matter. A stage should describe a meaningful change in the buying process, supported by observable evidence. “Proposal sent” describes seller activity. “Decision process confirmed” describes progress that changes the likelihood and next action.': 'É por isso que as definições das etapas importam. Uma etapa deve descrever uma mudança significativa no processo de compra, suportada por evidência observável. “Proposta enviada” descreve atividade do vendedor. “Processo de decisão confirmado” descreve progresso que altera a probabilidade e a próxima ação.',
  'Which layer is limiting your revenue?': 'Que camada está a limitar a sua receita?', 'Use the assessment to compare Strategy, Process, CRM, Data, Automation and AI before choosing the intervention.': 'Use o diagnóstico para comparar Estratégia, Processo, CRM, Dados, Automação e IA antes de escolher a intervenção.', 'Diagnose the system →': 'Diagnosticar o sistema →',
  'Run a constraint review before a demand push': 'Reveja as limitações antes de aumentar a procura', 'Take one recent cohort and follow it from first meaningful signal to closed outcome. Do not start with the dashboard total. Sample actual records and conversations. Compare what the process says should happen with what happened.': 'Escolha uma coorte recente e acompanhe-a desde o primeiro sinal relevante até ao resultado fechado. Não comece pelo total do dashboard. Analise registos e conversas reais. Compare o que o processo diz que deve acontecer com aquilo que aconteceu.',
  'Then identify the smallest number of explanations that account for most of the loss. Perhaps leads waited two days for ownership. Perhaps sales rejected a segment that marketing was rewarded for generating. Perhaps discovery captured needs but not decision criteria. Perhaps opportunities stayed open because the CRM had no clear exit rule.': 'Depois, identifique o menor número de explicações que justifique a maior parte da perda. Talvez os leads tenham esperado dois dias por um responsável. Talvez as vendas tenham rejeitado um segmento que o marketing era recompensado por gerar. Talvez o discovery tenha recolhido necessidades, mas não critérios de decisão. Talvez as oportunidades tenham ficado abertas porque o CRM não tinha uma regra de saída clara.',
  'Each of these requires a different response. More media spend will not fix ownership. More sales activity will not fix conflicting definitions. A new dashboard will not fix missing evidence.': 'Cada uma destas situações exige uma resposta diferente. Mais investimento em media não corrige a responsabilidade. Mais atividade comercial não corrige definições em conflito. Um novo dashboard não corrige evidência em falta.',
  'When more pipeline is the right answer': 'Quando mais pipeline é a resposta certa', 'Increase demand when the system demonstrates that it can convert additional suitable demand without disproportionate loss. That means the ICP is clear, stages carry evidence, ownership is timely, capacity is available and the economics remain credible.': 'Aumente a procura quando o sistema demonstrar que consegue converter procura adequada adicional sem perdas desproporcionadas. Isso significa que o ICP é claro, as etapas contêm evidência, a responsabilidade é atempada, existe capacidade e a economia continua credível.', 'Growth then becomes a controlled expansion of a functioning system rather than a bet that volume will overwhelm the weaknesses underneath it.': 'O crescimento torna-se então uma expansão controlada de um sistema funcional, em vez de uma aposta em que o volume ultrapasse as fragilidades subjacentes.',
  'Use this when': 'Utilize quando', 'Pipeline is below plan, acquisition costs are rising or teams disagree about the source of the shortfall.': 'O pipeline está abaixo do plano, os custos de aquisição estão a subir ou as equipas discordam sobre a origem da quebra.', 'Explore Strategy →': 'Explorar Estratégia →',

  'Revenue Leaks at the Hand-offs — RevOpHubs': 'A receita perde-se nas passagens de trabalho — RevOpHubs', 'Most cross-functional loss is not dramatic. It appears as waiting, missing context, repeated work and decisions that nobody explicitly owns.': 'A maior parte da perda entre funções não é dramática. Surge como espera, contexto em falta, trabalho repetido e decisões pelas quais ninguém é explicitamente responsável.',
  'Inside each function, the work may appear healthy. Marketing delivers leads. Sales accepts them. Customer success receives the signed customer. Yet the customer experiences one journey, not the organisation chart. Every transition between teams creates a moment where context, time and accountability can disappear.': 'Dentro de cada função, o trabalho pode parecer saudável. O marketing entrega leads. As vendas aceitam-nos. Customer success recebe o cliente contratado. Mas o cliente vive uma jornada, não o organograma. Cada transição entre equipas cria um momento em que o contexto, o tempo e a responsabilização podem desaparecer.',
  'A hand-off is a decision, not a notification': 'Uma passagem de trabalho é uma decisão, não uma notificação', 'Many processes define a hand-off as the moment a record changes owner or a notification is sent. That describes system activity. A real hand-off is complete only when the receiving team has the information, authority and capacity to perform the next work.': 'Muitos processos definem uma passagem de trabalho como o momento em que um registo muda de responsável ou é enviada uma notificação. Isso descreve atividade do sistema. Uma passagem real só está concluída quando a equipa recetora tem a informação, a autoridade e a capacidade para executar o trabalho seguinte.',
  'That requires four elements: an explicit trigger, required context, a named receiving owner and a confirmation that the work has been accepted. Without these, the sender believes the work moved while the receiver still needs to interpret or reconstruct it.': 'Isso exige quatro elementos: um trigger explícito, o contexto necessário, um responsável recetor identificado e a confirmação de que o trabalho foi aceite. Sem estes elementos, quem envia acredita que o trabalho avançou enquanto quem recebe ainda precisa de o interpretar ou reconstruir.', 'The most expensive hand-off is the one both teams believe the other team owns.': 'A passagem de trabalho mais cara é aquela que ambas as equipas acreditam ser responsabilidade da outra.',
  'Look for failure demand': 'Procure procura gerada por falhas', 'Failure demand is work created because the process did not work correctly the first time. It includes chasing missing information, re-qualifying a lead, correcting a contract detail, rebuilding a forecast category or explaining a promise that was never recorded.': 'A procura gerada por falhas é trabalho criado porque o processo não funcionou corretamente à primeira. Inclui procurar informação em falta, requalificar um lead, corrigir um detalhe contratual, reconstruir uma categoria de previsão ou explicar uma promessa que nunca foi registada.',
  'These tasks are often invisible in dashboards because they occur in messages, meetings and private notes. Observe a sample of recent hand-offs and count the extra interactions required before the receiving team could act. The volume of rework is a direct measure of process quality.': 'Estas tarefas são muitas vezes invisíveis nos dashboards porque acontecem em mensagens, reuniões e notas privadas. Observe uma amostra de passagens recentes e conte as interações adicionais necessárias até a equipa recetora poder agir. O volume de retrabalho é uma medida direta da qualidade do processo.',
  'Is Process your limiting layer?': 'O Processo é a sua camada limitadora?', 'The Revenue System Assessment compares process strength with the five layers around it.': 'O diagnóstico do sistema de receita compara a força do processo com as cinco camadas à sua volta.',
  'Map one critical transition': 'Mapeie uma transição crítica', 'Do not begin by documenting the entire customer lifecycle. Choose the hand-off with the strongest combination of volume, delay and commercial consequence. Map what happens now using actual records rather than the official process diagram.': 'Não comece por documentar todo o ciclo de vida do cliente. Escolha a passagem de trabalho com a combinação mais forte de volume, atraso e consequência comercial. Mapeie o que acontece agora usando registos reais em vez do diagrama oficial do processo.', 'For that transition, answer:': 'Para essa transição, responda:',
  'What observable event should trigger the hand-off?': 'Que evento observável deve iniciar a passagem de trabalho?', 'Which information must be present and trustworthy?': 'Que informação tem de estar presente e ser fiável?', 'Who accepts the work, and within what response time?': 'Quem aceita o trabalho e em que prazo de resposta?', 'What happens when the criteria are not met?': 'O que acontece quando os critérios não são cumpridos?', 'Which measure shows whether the hand-off improved?': 'Que métrica mostra se a passagem melhorou?',
  'Automation comes after agreement': 'A automação vem depois do acordo', 'It is tempting to solve a slow hand-off with routing rules and alerts. Automation is useful when the rules are stable and exceptions are understood. When teams disagree about criteria or ownership, automation removes the conversation without resolving the disagreement.': 'É tentador resolver uma passagem lenta com regras de encaminhamento e alertas. A automação é útil quando as regras são estáveis e as exceções são compreendidas. Quando as equipas discordam sobre critérios ou responsabilidade, a automação elimina a conversa sem resolver o desacordo.',
  'First establish the operational contract between sender and receiver. Test it manually for a short period. Observe exceptions. Then automate the stable parts and preserve a visible route for cases that require judgement.': 'Primeiro, estabeleça o contrato operacional entre quem envia e quem recebe. Teste-o manualmente durante um curto período. Observe as exceções. Depois, automatize as partes estáveis e mantenha um caminho visível para os casos que exigem julgamento.',
  'Review the customer consequence': 'Reveja a consequência para o cliente', 'An internal process can appear efficient while creating a poor customer experience. A fast sales-to-onboarding hand-off is not successful if the customer has to repeat the context, objectives and concerns already discussed during the sale.': 'Um processo interno pode parecer eficiente enquanto cria uma má experiência para o cliente. Uma passagem rápida de vendas para onboarding não é bem-sucedida se o cliente tiver de repetir o contexto, os objetivos e as preocupações já discutidos durante a venda.', 'Include the customer consequence in the hand-off measure: time to first value, repeated questions, expectation gaps and early support demand. This keeps optimisation connected to revenue rather than administrative speed alone.': 'Inclua a consequência para o cliente na métrica da passagem: tempo até ao primeiro valor, perguntas repetidas, falhas de expectativas e procura precoce de suporte. Assim, a otimização mantém-se ligada à receita e não apenas à velocidade administrativa.',
  'Explore the Process layer →': 'Explorar a camada de Processo →', 'Map these four': 'Mapeie estes quatro elementos', 'Trigger, context, owner and acceptance.': 'Trigger, contexto, responsável e aceitação.', 'Browse tools →': 'Ver ferramentas →',

  'CRM Adoption Is an Operating-Design Issue — RevOpHubs': 'A adoção do CRM é uma questão de desenho operacional — RevOpHubs', 'Check CRM readiness': 'Testar preparação do CRM', 'People avoid systems that ask for work without helping them work. Training cannot repair that exchange.': 'As pessoas evitam sistemas que lhes pedem trabalho sem as ajudar a trabalhar. A formação não consegue corrigir essa relação.',
  'When CRM adoption is low, the standard response is more training, more required fields or stronger management enforcement. Each may produce a temporary increase in completion. None necessarily makes the system more useful.': 'Quando a adoção do CRM é baixa, a resposta habitual é mais formação, mais campos obrigatórios ou maior pressão da gestão. Cada uma destas medidas pode produzir um aumento temporário no preenchimento. Nenhuma torna necessariamente o sistema mais útil.',
  'Adoption is often treated as a user-attitude problem. In practice, users make a rational judgement: does the CRM help me understand what matters, act faster and avoid rework — or does it mainly collect information for someone else?': 'A adoção é frequentemente tratada como um problema de atitude dos utilizadores. Na prática, os utilizadores fazem um julgamento racional: o CRM ajuda-me a compreender o que importa, a agir mais depressa e a evitar retrabalho — ou serve sobretudo para recolher informação para outra pessoa?',
  'The CRM is downstream of operating choices': 'O CRM vem depois das escolhas operacionais', 'A CRM cannot decide what qualifies an opportunity, who owns a hand-off or which evidence should move a deal forward. It can only express those decisions. If the organisation has not made them, configuration fills the gap with assumptions.': 'Um CRM não pode decidir o que qualifica uma oportunidade, quem é responsável por uma passagem de trabalho ou que evidência deve fazer avançar um negócio. Só pode expressar essas decisões. Se a organização ainda não as tomou, a configuração preenche a lacuna com pressupostos.',
  'This creates familiar symptoms: dozens of fields with unclear purpose, stages based on seller activity, automations that surprise users and reports that require manual reconciliation. Training teaches people how to navigate the symptoms. It does not remove them.': 'Isto cria sintomas familiares: dezenas de campos com finalidade pouco clara, etapas baseadas na atividade do vendedor, automações que surpreendem os utilizadores e relatórios que exigem reconciliação manual. A formação ensina as pessoas a navegar os sintomas. Não os elimina.', 'Adoption improves when the CRM becomes the shortest path to doing the work correctly.': 'A adoção melhora quando o CRM se torna o caminho mais curto para fazer o trabalho corretamente.',
  'Design around decisions, not data collection': 'Desenhe em torno de decisões, não da recolha de dados', 'Start by listing the decisions a user must make at each stage. A salesperson may need to decide whether an account fits, what evidence is missing and which next action is appropriate. A manager may need to decide where to coach, where to intervene and whether the forecast is credible.': 'Comece por listar as decisões que um utilizador tem de tomar em cada etapa. Um vendedor pode precisar de decidir se uma conta se adequa, que evidência falta e qual é a próxima ação apropriada. Um gestor pode precisar de decidir onde orientar, onde intervir e se a previsão é credível.',
  'Only then ask which information supports those decisions. This reverses the usual sequence. Instead of collecting data because it might be useful, the system captures what is necessary for a defined action or judgement.': 'Só depois pergunte que informação suporta essas decisões. Isto inverte a sequência habitual. Em vez de recolher dados porque podem vir a ser úteis, o sistema captura o que é necessário para uma ação ou julgamento definidos.',
  'Are you ready to redesign the CRM?': 'Está preparado para redesenhar o CRM?', 'The readiness check tests nine operating conditions before configuration or migration begins.': 'O teste de preparação avalia nove condições operacionais antes de começar a configuração ou migração.', 'Run the CRM Readiness Check →': 'Fazer o teste de preparação do CRM →',
  'Observe work outside the CRM': 'Observe o trabalho fora do CRM', 'Spreadsheets, private notes and messaging threads are not merely resistance. They are evidence. They show where the official system fails to support the work: faster collaboration, missing context, flexible planning or a view the CRM does not provide.': 'Folhas de cálculo, notas privadas e conversas em aplicações de mensagens não são apenas resistência. São evidência. Mostram onde o sistema oficial não suporta o trabalho: colaboração mais rápida, contexto em falta, planeamento flexível ou uma visão que o CRM não oferece.',
  'Do not ban these workarounds before understanding them. Observe which job they perform better. The goal is not to force every activity into the CRM. It is to decide which information and actions must be shared for the revenue system to function.': 'Não proíba estas soluções alternativas antes de as compreender. Observe que trabalho fazem melhor. O objetivo não é forçar todas as atividades para dentro do CRM. É decidir que informação e ações têm de ser partilhadas para o sistema de receita funcionar.',
  'Governance keeps adoption from decaying': 'A governação evita a degradação da adoção', 'Even a strong design degrades when anyone can add fields, change stages or build overlapping automations. CRM governance does not need to be bureaucratic. It needs a clear owner, a change process and a test for whether a request improves a real workflow or decision.': 'Mesmo um desenho sólido degrada-se quando qualquer pessoa pode acrescentar campos, alterar etapas ou criar automações sobrepostas. A governação do CRM não tem de ser burocrática. Precisa de um responsável claro, de um processo de mudança e de um teste para determinar se um pedido melhora um fluxo de trabalho ou decisão reais.',
  'A useful governance review asks: Who benefits? Which behaviour should change? What existing field or workflow does this replace? How will we know that the change works? If nobody can answer, the request is not ready for configuration.': 'Uma revisão de governação útil pergunta: Quem beneficia? Que comportamento deve mudar? Que campo ou fluxo de trabalho existente é substituído? Como saberemos que a mudança funciona? Se ninguém conseguir responder, o pedido não está pronto para configuração.',
  'Measure behaviour and value together': 'Meça comportamento e valor em conjunto', 'Login rates and field completion measure compliance. Pair them with measures of user value and system performance: time to next action, completeness at hand-off, forecast change, duplicated work and the proportion of records that require manual correction.': 'As taxas de login e o preenchimento de campos medem conformidade. Combine-as com métricas de valor para o utilizador e desempenho do sistema: tempo até à próxima ação, completude na passagem de trabalho, alteração da previsão, trabalho duplicado e proporção de registos que exigem correção manual.',
  'Adoption is not the final goal. A trusted, useful operating system is. Adoption is the behaviour that follows when the design earns it.': 'A adoção não é o objetivo final. Um sistema operativo útil e de confiança é. A adoção é o comportamento que surge quando o desenho o merece.', 'Three tests': 'Três testes', 'Does the CRM guide decisions? Does it reduce rework? Does it make hand-offs verifiable?': 'O CRM orienta decisões? Reduz o retrabalho? Torna verificáveis as passagens de trabalho?', 'Check readiness →': 'Testar preparação →', 'Explore the CRM layer →': 'Explorar a camada de CRM →',

  'AI Readiness Starts Before the AI Layer — RevOpHubs': 'A preparação para IA começa antes da camada de IA — RevOpHubs', 'AI does not sit above a revenue system and repair it. It inherits the system’s context, rules, data quality and accountability.': 'A IA não se coloca acima de um sistema de receita para o reparar. Herda o contexto, as regras, a qualidade dos dados e a responsabilização do sistema.',
  'Organisations often assess AI readiness by counting tools, licences or experiments. This measures access, not readiness. A team can use several AI assistants every day while the organisation remains unable to deploy AI reliably inside the workflows that create revenue.': 'As organizações avaliam muitas vezes a preparação para IA contando ferramentas, licenças ou experiências. Isto mede acesso, não preparação. Uma equipa pode usar vários assistentes de IA todos os dias enquanto a organização continua incapaz de implementar IA de forma fiável nos fluxos de trabalho que criam receita.',
  'Operational readiness begins in the layers before AI: clear commercial choices, repeatable processes, useful CRM context, trusted data and governed automation. AI amplifies the quality of that foundation.': 'A preparação operacional começa nas camadas anteriores à IA: escolhas comerciais claras, processos repetíveis, contexto útil no CRM, dados fiáveis e automação governada. A IA amplifica a qualidade dessa base.',
  'Useful AI needs bounded work': 'A IA útil precisa de trabalho delimitado', '“Help sales” is not a workflow. “Prepare a first-draft meeting brief using the account record, recent conversations and open opportunities” is. The second statement defines an input, an action, an output and a moment for human judgement.': '“Ajudar as vendas” não é um fluxo de trabalho. “Preparar um primeiro rascunho do briefing da reunião usando o registo da conta, conversas recentes e oportunidades abertas” é. A segunda frase define um input, uma ação, um resultado e um momento para julgamento humano.',
  'AI initiatives become operational when the work is narrow enough to observe. Teams can evaluate whether the output is accurate, whether it saves time, what context is missing and which exceptions require escalation.': 'As iniciativas de IA tornam-se operacionais quando o trabalho é suficientemente específico para ser observado. As equipas podem avaliar se o resultado é exato, se poupa tempo, que contexto falta e que exceções exigem escalamento.',
  'The goal is not to automate more work. It is to design a revenue system worth automating.': 'O objetivo não é automatizar mais trabalho. É desenhar um sistema de receita que valha a pena automatizar.', 'Context is an operating asset': 'O contexto é um ativo operacional',
  'AI output is only as specific as the context available to it. That context includes more than CRM fields. It includes definitions, customer evidence, policies, product knowledge, previous decisions and the current state of the workflow.': 'O resultado da IA só é tão específico quanto o contexto disponível. Esse contexto inclui mais do que campos do CRM. Inclui definições, evidência do cliente, políticas, conhecimento do produto, decisões anteriores e o estado atual do fluxo de trabalho.',
  'If this information is scattered, contradictory or inaccessible, users compensate by repeatedly explaining the business to a general-purpose assistant. The result may sound competent but remains detached from how the organisation actually works.': 'Se esta informação estiver dispersa, for contraditória ou inacessível, os utilizadores compensam explicando repetidamente o negócio a um assistente generalista. O resultado pode parecer competente, mas permanece desligado da forma como a organização realmente trabalha.',
  'How strong is the AI layer around your system?': 'Quão sólida é a camada de IA do seu sistema?', 'The assessment identifies whether AI is the current constraint or whether an earlier layer deserves attention first.': 'O diagnóstico identifica se a IA é a limitação atual ou se uma camada anterior merece atenção primeiro.',
  'Human ownership cannot be automated away': 'A responsabilidade humana não pode ser automatizada', 'Every AI-supported workflow needs an owner who defines acceptable quality, reviews failure patterns and decides how the system should change. “Human in the loop” is not enough if the human is unnamed, overloaded or unable to reject the output.': 'Cada fluxo de trabalho suportado por IA precisa de um responsável que defina a qualidade aceitável, reveja padrões de falha e decida como o sistema deve mudar. “Humano no circuito” não é suficiente se essa pessoa não estiver identificada, estiver sobrecarregada ou não puder rejeitar o resultado.',
  'Define three boundaries: what the AI may propose, what it may execute with review and what it must never do without an explicit human decision. These boundaries should reflect commercial risk, reversibility and the quality of available context.': 'Defina três limites: o que a IA pode propor, o que pode executar com revisão e o que nunca pode fazer sem uma decisão humana explícita. Estes limites devem refletir o risco comercial, a reversibilidade e a qualidade do contexto disponível.',
  'Measure capacity, quality and rework': 'Meça capacidade, qualidade e retrabalho', 'Time saved is useful but incomplete. An AI workflow can produce output faster while increasing review effort, inconsistency or downstream correction. Measure the full exchange:': 'O tempo poupado é útil, mas incompleto. Um fluxo de IA pode produzir resultados mais depressa enquanto aumenta o esforço de revisão, a inconsistência ou a correção posterior. Meça toda a troca:', 'Time from input to usable output.': 'Tempo desde o input até a um resultado utilizável.', 'Proportion accepted without material correction.': 'Proporção aceite sem correção material.', 'Errors or omissions by category.': 'Erros ou omissões por categoria.', 'Rework created downstream.': 'Retrabalho criado a jusante.', 'Capacity redirected to higher-value work.': 'Capacidade redirecionada para trabalho de maior valor.',
  'A 30-day operational test': 'Um teste operacional de 30 dias', 'Choose one repeated workflow with a clear owner, trustworthy inputs and frequent enough volume to learn quickly. Define the current baseline. Run the AI-supported version with human review. Record corrections and exceptions, not just successes.': 'Escolha um fluxo de trabalho repetido com um responsável claro, inputs fiáveis e volume suficientemente frequente para aprender depressa. Defina a baseline atual. Execute a versão suportada por IA com revisão humana. Registe correções e exceções, não apenas sucessos.',
  'At the end of four weeks, decide whether to improve context, change the workflow, narrow the use case or scale it. This turns AI adoption into operational learning instead of a collection of demonstrations.': 'Ao fim de quatro semanas, decida se deve melhorar o contexto, alterar o fluxo de trabalho, restringir o caso de uso ou escalá-lo. Isto transforma a adoção de IA em aprendizagem operacional, em vez de numa coleção de demonstrações.',
  'Explore the AI layer →': 'Explorar a camada de IA →', 'RevOps is an operating system →': 'RevOps é um sistema operativo →', 'Readiness test': 'Teste de preparação', 'Bounded work, trusted context, named owner and measurable quality.': 'Trabalho delimitado, contexto fiável, responsável identificado e qualidade mensurável.', 'Research agenda →': 'Agenda de investigação →'
}));

const attributeNames = ['content', 'aria-label', 'title'];

function translateHtml(source, relative) {
  let html = source.replaceAll('https://revopshubs.com', 'https://revophubs.com').replaceAll('hello@revopshubs.com', 'hello@revophubs.com');
  html = html.replace('<html lang="en">', '<html lang="pt-PT">');
  html = html.split(/(<[^>]+>)/g).map((part) => {
    if (part.startsWith('<')) return part;
    const match = part.match(/^(\s*)([\s\S]*?)(\s*)$/);
    const value = match[2].replace(/\s+/g, ' ').trim();
    return value && t.has(value) ? `${match[1]}${t.get(value)}${match[3]}` : part;
  }).join('');
  for (const name of attributeNames) {
    html = html.replace(new RegExp(`${name}="([^"]+)"`, 'g'), (full, value) => t.has(value) ? `${name}="${t.get(value)}"` : full);
  }
  html = html.replace(/href="\/(?!\/|pt\/|styles\.css|content\.css|favicon\.svg|app\.js)([^"]*)"/g, 'href="/pt/$1"');
  html = html.replace(/href="\/"/g, 'href="/pt/"');
  const canonicalPath = relative === 'index.html' ? '' : relative;
  html = html.replace(/<link rel="canonical" href="[^"]+">/, `<link rel="canonical" href="https://revophubs.com/pt/${canonicalPath}">`);
  return html;
}

for (const relative of pages) {
  const sourceFile = path.join(root, relative);
  const source = fs.readFileSync(sourceFile, 'utf8').replace(/<!-- language-switch:start -->[\s\S]*?<!-- language-switch:end -->/g, '');
  const destination = path.join(root, 'pt', relative);
  fs.mkdirSync(path.dirname(destination), { recursive: true });
  const englishPath = relative === 'index.html' ? '/' : `/${relative}`;
  const portuguesePath = relative === 'index.html' ? '/pt/' : `/pt/${relative}`;
  const englishSwitch = `<!-- language-switch:start --><a class="language-switch" href="${portuguesePath}" lang="pt-PT" hreflang="pt-PT" aria-label="Ver em português">PT</a><!-- language-switch:end -->`;
  const portugueseSwitch = `<!-- language-switch:start --><a class="language-switch" href="${englishPath}" lang="en" hreflang="en" aria-label="Ver em inglês">EN</a><!-- language-switch:end -->`;
  fs.writeFileSync(sourceFile, source.replace('</nav>', `</nav>${englishSwitch}`));
  fs.writeFileSync(destination, translateHtml(source, relative).replace('</nav>', `</nav>${portugueseSwitch}`));
}

console.log(`Built ${pages.length} Portuguese pages.`);
